#!/bin/bash

sudo apt-get update
sudo apt-get -y upgrade

sudo apt-get install -y python3.6
sudo apt-get install -y python3-pip
sudo apt-get install -y python3-dev
sudo apt-get install -y build-essential
sudo apt-get install -y libssl-dev
sudo apt-get install -y libffi-dev

sudo snap install --classic code
sudo pip3 install pylint

sudo apt-get install -y git

git clone https://github.com/PRO3-SIB19/Zero-Day-IP-Blacklist

cd Zero-Day-IP-Blacklist
sudo pip3 install -U -r requirements.txt

cd ..
sudo code --user-data-dir = ~/code_profiles/heralding/data
